### ISSUE TITLE
Async disposal (Feature Request)

### ISSUE THREAD

**Issue by TomPeters** [Dasync/AsyncEnumerable#11]
While creation of the enumerator (`GetAsyncEnumeratorAsync`) and moving next (`MoveNextAsync`) are asynchronous, disposal of the enumerator is currently synchronous and cannot be done in an asynchronous way.

Given that the you are likely to be doing asynchronous operations if you are using this library in the first place, it is likely that you could have some asynchronous cleanup after you finish enumerating. I have certainly encountered this in my usage of this library.

Consider this example: 

    public static IAsyncEnumerable<int> GetRows()
    {
        return new AsyncEnumerable<int>(async yield =>
        {
            IConnection connection = CreateConnection();
            try
            {
                var rows = await connection.GetDataAsync();
                foreach (var row in rows)
                    await yield.ReturnAsync(row);
            }
            finally
            {
                await connection.Close();
            }
        });
    }

    interface IConnection
    {
        Task Close();
        Task<IEnumerable<int>> GetDataAsync();
    }

Calling `Dispose()` on an enumerator in this example will set the exception on the `TaskCompletionSource` that is being awaited on by `yield.ReturnAsync`. So the dispose action of closing the connection will indeed be run, but this will happen sometime after `Dispose()` has been called, and nothing will be awaiting on the result of this. This may be problematic in cases where you are relying on the underlying resources being disposed when you have finished with the enumerator.

So what do you think about adding some way of awaiting the result of asynchronously disposing the enumerator?

I suggest that `IAsyncEnumerator` continues to implement `IDisposable`, but add another property to `IAsyncEnumerator` like the following:

    public interface IAsyncENumerator : IDisposable
    {
        object Current { get; }
        Task<bool> MoveNextAsync(CancellationToken cancellationToken = default(CancellationToken));
        Task Disposal { get; }
    }

This allows you to await on the disposal if you wish, but if you don't care about when the disposal happens, you can chose to not await anything (i.e. the current behavior). This approach is described in this blog post https://blog.stephencleary.com/2013/03/async-oop-6-disposal.html

Any extension methods on `IAsyncEnumerable` should probably be awaiting the disposal of the underlying enumerator as well.

If you think this is a good idea, I would be happy to work on this.

**Comment by tyrotoxin** [comment]
I agree, sometimes such async disposal is needed indeed. Personally, I found that problem in `CryptoStream` and `DeflateStream`, which write a final portion of data on `Dispose` only, which is always synchronous.
However, I'm hesitant to add such property to the interface at this point. You have a workaround like this (not ideal, but works):
```csharp
public static IAsyncEnumerator<int> GetRows()
{
    IConnection connection = CreateConnection();
    return new AsyncEnumerator<int>(async yield =>
    {
        var rows = await connection.GetDataAsync();
        foreach (var row in rows)
            await yield.ReturnAsync(row);
    },
    onDispose: ()=> connection.Close().Wait());
}
```

**Comment by TomPeters** [comment]
> However, I'm hesitant to add such property to the interface at this point.

Is this because it seems to pollute an otherwise simple API? Or is there another reason? The nice thing about adding an extra property to `IAsyncEnumerator` is that it won't break any existing code, so it is a relatively 'safe' thing to add.

**Comment by tyrotoxin** [comment]
@TomPeters, this issue has been addressed in the latest version 3 of this library:
https://www.nuget.org/packages/AsyncEnumerator/3.0.0-beta1
As of now, it's marked as 'beta' since .NET Core 3.0 is still in preview. Otherwise, it's a properly working release.

The new interface `IAsyncDisposable` has been introduced, and all extension methods (like `ForEachAsync` or `ParallelForEachAsync`) use it to await for the enumerator's finalization.

Please note that there are other breaking changes - the library now replicates Microsoft's version of `IAsyncEnumerable` and `IAsyncEnumerator` interfaces.
