### ISSUE TITLE
System is a reserved namespace

### ISSUE THREAD

**Issue by kabua** [Dasync/AsyncEnumerable#14]
We would love to use this library but we can't since it is currently in the System namespace.

According to the C# standards (defined by [ECMA Standards 334](http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-334.pdf) ) in section 16.2 (page 252) it states:

```Fully qualified names beginning with System. are reserved for use by the Standard Library (§Annex D). ```

Therefore, to be compliant with the .NET standards and to support a wider audience please move the great library to its own namespace.

Thank you.

**Comment by stil** [comment]
I'm also voting for a change to non-System namespace. Additionally, I get an error

> 'IAsyncEnumerator<>' is an ambiguous reference between 'System.Collections.Async.IAsyncEnumerator<T>' and 'System.Collections.Generic.IAsyncEnumerator<T>'

For example `List<T>` is from `System.Collections.Generic`, so it causes overlap and I need to use full qualified name either for `List<T>` or `IAsyncEnumerator<T>`.

Can we get a yes or no whether this issue could be solved?

**Comment by tyrotoxin** [comment]
That makes sense, even if it reduces usability. That will be done with the next major release, because this is a breaking change.

**Comment by TechInterMezzo** [comment]
Are there any news on this topic or suggestions for the name clash mentioned by @stil ?
It's quite a pain that C# only supports alias for closed generic types in this situation.

**Comment by tyrotoxin** [comment]
@TechInterMezzo, the latest version of this library has been adapted for the .NET Core 3, which eliminates the name collision problem: https://www.nuget.org/packages/AsyncEnumerator/3.0.2-beta

The version 3.0.2-beta is completely stable, but marked as a pre-release since .NET Core 3 is not released yet. However, there are no changes to namespaces.

**Comment by kind-serge** [comment]
With the latest release of v3 all types have been moved to `Dasync.Collections` namespace.
