### ISSUE TITLE
Creating an IAsyncEnumerable from a Task (feature request)

### ISSUE THREAD

**Issue by julian-goldsmith** [Dasync/AsyncEnumerable#25]
It might be useful to add an IAsyncEnumerable constructor that takes a `Task<IEnumerable<T>>`, and possibly `Task<IAsyncEnumerable<T>>`.  That would make it so that you don't have to mix `async` and `IAsyncEnumerable` if you have `async` code that gets your `IEnumerable`.

A (currently-untested) example of what I mean would be something like:
```csharp
private IAsyncEnumerable<T> CreateAsyncEnumerableFromTask<T>(Func<Task<IEnumerable<T>>> enumerableFunction)
{
	return new AsyncEnumerable<T>(async yield =>
	{
		IEnumerable<T> items = await enumerableFunction();

		foreach (T item in items)
		{
			await yield.ReturnAsync(item);
		}
	});
}
```

That could probably be implemented much better if it was included in the library itself, maybe as an `AsyncEnumerable<T>` constructor, or an extension method on `Task<IEnumerable<T>>`.

An example of how it could be used (really, a distilled version of how I'm going to use the above method) would be:
```csharp
return CreateAsyncEnumerableFromTask(async delegate
{
	string response = await RunRequest(requestParameters);
	return Deserialize(response);
});
```

**Comment by tyrotoxin** [comment]
I think you can simplify the problem, where don't actually need that feature, and where you don't need `SelectMany` at all. I would just hide batching in such way:
```csharp
public IAsyncEnumerable<Item> ExtractAsync(object[] parameters) =>
new AsyncEnumerable<Item>(async yield =>
{
  // Produce request batches.
  foreach (var batchRequest in GetBatchedRequests(parameters))
  {
    // Fetch items in a batch (pre-load a batch into memory).
    var items = await RunBatchedRequest(batchRequest);
    // Yield items.
    foreach (var item in items)
      await yield.ReturnAsync(item);
  }
});
```

**Comment by julian-goldsmith** [comment]
Thanks, @tyrotoxin.  I had been trying to use `ToAsyncEnumerable` and `SelectMany` to try to simplify my code, but it seems like it had the opposite effect.  I like your approach better.
