### ISSUE TITLE
FEATURE: IOrderedAsyncEnumerable implementation

### ISSUE THREAD

**Issue by otabekgb** [Dasync/AsyncEnumerable#28]
Do you have a plan for this?

**Comment by tyrotoxin** [comment]
what does it supposed to do?

**Comment by otabekgb** [comment]
With it you can order the sequence. Sync version is IOrderedEnumerable

**Comment by tyrotoxin** [comment]
An `IAsyncEnumerable` should be used for streaming, not sure how `IOrderedEnumerable` can be applicable here - the source collection should not be stored in memory.
Do you have any specific use case?

**Comment by ndrwrbgs** [comment]
@tyrotoxin It's possible in a streaming context - similar to `IQbservable` - where it is really the remote that is doing the sorting and it's just a signal to the consumer that it IS sorted, but no code in a library would ever be making a `OrderedAsyncEnumerable` directly.

> To explain that better, a client would call a StreamSortedFromRemote(). The remote would create an IOrderedEnumerable, but then stream that back to the client (probably in batches). In this way, there's no concrete implementation of the `OrderedAsyncEnumerable`, but the interface does allow for some assumptions made in e.g. extension methods.

That said, I'm not sure what scenario this would enable that couldn't be accomplished by the calling code just assuming that the collection is ordered. The scenarios I can think of seem to be suited for
* Task<IOrderedEnumerable>
* IAsyncEnumerable
* Quite specific to a particular scenario making it probably best to just make that 'assumption' of sorted in the client code.

@otabekgb could you explain the scenario you'd need this for, for better musing about the solutions?

**Comment by tyrotoxin** [comment]
@otabekgb, I'm closing the suggestion due to lack of the input. Feel free to open if you have a concrete scenario.
