### ISSUE TITLE
yield.Break() leads to TaskCanceledException

### ISSUE THREAD

**Issue by Deni35** [Dasync/AsyncEnumerable#30]
Look at next code:

        var e = GetItems().GetAsyncEnumeratorAsync().Result;
        e.MoveNextAsync().Wait();
        e.MoveNextAsync().Wait(); // this line throws: TaskCanceledException: A task was canceled.

        private static IAsyncEnumerable<int> GetItems() {
            return new AsyncEnumerable<int>( GetItems );
        }

        private static async Task GetItems(AsyncEnumerator<int>.Yield yield) {
            await Task.Delay( 1 );
            await yield.ReturnAsync( 0 );

            yield.Break(); // break

            await Task.Delay( 1 );
            await yield.ReturnAsync( 1 );
        }

IEnumerable<T>.MoveNext() returns just false when enumerator is ended with yeild.  So I decided it's bug or strange behavior.

**Comment by Deni35** [comment]
IAsyncEnumerable.ForEachAsync( ... ).Wait() also leads to exception. And it's real problem.

**Comment by tyrotoxin** [comment]
@Deni35, yes, it's a bug indeed. The problem has been fixed and the new version 2.2.2 is available here:
https://www.nuget.org/packages/AsyncEnumerator/2.2.2
