### ISSUE TITLE
Why does IEnumerable<Task<T>>.ToAsyncEnumerable() not return IAsyncEnumerable<T> ?

### ISSUE THREAD

**Issue by Deni35** [Dasync/AsyncEnumerable#31]
I think it is expected that ToAsyncEnumerable() will return `IAsyncEnumerable<T>`. But it returns `IEnumerable<Task<T>>`.

        // Examples
        GetDataTasks().ToAsyncEnumerable().ForEachAsync( data => { // expected and desired behavior
                Console.WriteLine( data );
        } );

        GetDataTasks().ToAsyncEnumerable().ForEachAsync( async i => { // actual behavior
                Console.WriteLine( await i );
        } );

        // Requests
        private static IEnumerable<Task<int>> GetDataTasks(int start = 0, int count = 1000) {
            return Enumerable.Range( start, count ).Select( GetDataAsync );
        }

        private static async Task<int> GetDataAsync(int id) { // simulate request to web service
            await Task.Delay( rnd.Next( 100, 2000 ) );
            return id;
        }

**Comment by tyrotoxin** [comment]
@Deni35, this is the expected behavior.
The extension method `ToAsyncEnumerable` is designed to convert an `IEnumerable<T>` to an `IAsyncEnumerable<T>`. In your case the generic argument `T` is `Task<int>`.
