### ISSUE TITLE
ParallelForEachAsync not awaiting

### ISSUE THREAD

**Issue by Simba-Mupfunya** [Dasync/AsyncEnumerable#34]
Hi shouldnt you define ParallelForEachAsync as async with await on Task.Run. By not doing this when i await ParallelForEachAsync it acutally continues to the next code block as the internal Task.Run is not awaited

`async public static Task ParallelForEachAsync<T>(
            this IAsyncEnumerable<T> collection,
            Func<T, long, Task> asyncItemAction,
            int maxDegreeOfParalellism,
            bool breakLoopOnException,
            bool gracefulBreak,
            CancellationToken cancellationToken = default)
        {
            ....
            await Task.Run
            ....
            await context.CompletionTask;
       }
`

**Comment by tyrotoxin** [comment]
@Simba-Mupfunya, can you clarify an issue you are experiencing?

**Comment by Simba-Mupfunya** [comment]
@tyrotoxin After futher digging i see you are using SemaphoreSlim to wait for the Task in the current context, so thats not an issue. The problem i was having is being caused by my async delegate thats defined on SQLite RunInTransactionAsync(**async conn**) which houses the code for ParallelForEachAsync. By defining the delegate as async as it doesnt implement a Func< Task > it basically in short means  RunInTransactionAsync does not await properly hence my operations that rely on my extremely large updates are compromised. This implementation was more a fact finding experimentation 

`await Context.RunInTransactionAsync(async conn => { 
                        await existingitems.ParallelForEachAsync(async itemToUpdate =>
                        {
                            ...
                        }, maxDegreeOfParalellism: 3).ConfigureAwait(false);
                    }).ConfigureAwait(false);`
