### ISSUE TITLE
Add ForEachAsync break equivalent (Feature Request)

### ISSUE THREAD

**Issue by MikeBeaton** [Dasync/AsyncEnumerable#35]
Hi,

I am finding this library extremely useful!

I have found one part of the `yield return` / `foreach` pattern which I *believe* isn't catered for yet.

If you are using `foreach (var item of items)` then you can put `break;` inside the loop to end early.

A pattern which I've made up for doing the equivalent is:

```
try
{
	await items.ForEachAsync(async item =>
	{
		// ... do stuff ...
		if (abort) throw new AsyncEnumerationCanceledException();
	});
}
catch (AsyncEnumerationCanceledException) { }
```

I wonder if it would be possible to support something like this instead:

```
await items.ForEachAsync(async item =>
{
	// ... do stuff ...
	if (abort) items.Break();
});
```

I'm imagining that my proposed  `IAsyncEnumerable<T>.Break()` method would do something like throw a new `ForEachAsyncCanceledException` which (as well as sending an `AsyncEnumerationCanceledException` into the enumeration function to allow cleanup, as all exceptions in the action function already do) would be seen and understood by `ForEachAsync` itself, meaning the outer catch in my manually coded version would no longer be needed.

Does this make sense? Am I missing something which does this already?

**Comment by tyrotoxin** [comment]
@MikeBeaton, thanks, and I appreciate putting the PR together!
I think this quick-fix is good enough, however I left 1 conceptual comment on the PR.

**Comment by tyrotoxin** [comment]
@MikeBeaton, thanks for the contribution. The change has been merged in, and new the version has been released: https://www.nuget.org/packages/AsyncEnumerator/3.0.2-beta

**Comment by MikeBeaton** [comment]
@tyrotoxin Hi, I just noticed that 3.0.2-beta is not tagged in this github repo, but probably should be? Thanks again!

**Comment by tyrotoxin** [comment]
@MikeBeaton , seems like you know how to support public repos better than me :) Thanks!

**Comment by MikeBeaton** [comment]
(Don't forget I'm coming from the side of being the public, in this case! 😉 😊)
