### ISSUE TITLE
asp.net core web api

### ISSUE THREAD

**Issue by mj430** [Dasync/AsyncEnumerable#39]
Will this library work with a web api implemented in asp.net core ?

**Comment by tyrotoxin** [comment]
absolutely

**Comment by mj430** [comment]
if i use your below sample code  then in postman  or chrome i see a blank resposne

   [HttpGet("api/testStream")]
        public async Task<System.Collections.Async.IAsyncEnumerable<int>> testStream()
           {
            return new AsyncEnumerable<int>(async yield =>
            {

                // Just to show that ReturnAsync can be used multiple times
                await yield.ReturnAsync(0);

                for (int number = 1; number <= 10; number++)
                    await yield.ReturnAsync(number);

                // You can break the enumeration loop with the following call:
                yield.Break();

                // This won't be executed due to the loop break above
                await yield.ReturnAsync(12345);
            });
        }

**Comment by tyrotoxin** [comment]
This is definitely is not a supported scenario as the ASP.NET framework does not know that the `IAsyncEnumerable` represents a collection. Your best option is:
```
[HttpGet("api/testStream")]
public async Task<List<int>> testStream()
{
    var collection = new AsyncEnumerable(async yield =>
    {
         await yield.ReturnAsync(12345);
    });
    return await collection.ToListAsync();
}
```

**Comment by mj430** [comment]
Thanks for the response. But if i do it as suggested by you. Then the web api will not return until  the call
return await collection.ToListAsync();.

So the client will not get the values as they are produced, they will get it when the whole list is made.

**Comment by tyrotoxin** [comment]
That's correct, the only other workaround, is to convert an `IAsyncEnumerable` to `IEnumerable`, what defeats the whole purpose. This feature most likely will be supported natively by ASP NET Core when C# 8.0 and .NET Core 3.0 are released.

**Comment by tyrotoxin** [comment]
@mj430, I'll have to close this issue as it goes beyond the scope of the current project. Perhaps it is possible to achieve the behavior that you want, but it should be a separate project that binds together ASP.NET Core MVC and AsyncEnumerable library.
