### ISSUE TITLE
Should MoveNextAsync/ReturnAsync be checking if the CancellationToken has been cancelled?

### ISSUE THREAD

**Issue by ndani14-zap** [Dasync/AsyncEnumerable#40]
I came across this behavior while writing some unit tests around some code that deals with batched data and I found it surprising. Just wondering what your take on it is? 

Linqpad sample
```csharp
async Task Main()
{
  using (var cts = new CancellationTokenSource())
    await PartialEnumerationCancelTest(cts)
        .ForEachAsync(x => x.Dump(), cts.Token);
}

IAsyncEnumerable<int> PartialEnumerationCancelTest(CancellationTokenSource cts)
{
  return new AsyncEnumerable<int>(async yield =>
  {
    foreach (var i in Enumerable.Range(0, 10))
    {
      // simulate a cancel part way through the enumeration
      if (i == 4) cts.Cancel();
      await yield.ReturnAsync(i);
    }
  });  
}
```

Linqpad Output
`0
1
2
3
4
5
6
7
8
9`

Linqpad Output I would have expected
`0
1
2
3
-- A task was canceled.
`

The same thing happens when manually enumerating. I would have expected `MoveNextAsync` to be checking the cancellation token.
```csharp
using (var cts = new CancellationTokenSource())
using (var enumerator = await PartialEnumerationCancelTest(cts).GetAsyncEnumeratorAsync(cts.Token))
  while (await enumerator.MoveNextAsync(cts.Token))
    enumerator.Current.Dump();
```

**Comment by tyrotoxin** [comment]
hi @ndani14-zap, by looking at the implementation, I see that I didn't add the check of a cancellation token to the for-each loop. To my best memory, I wanted to give an end-user the control of canceling the enumeration within the loop body itself to avoid any unexpected behavior.

The cancellation token is available through `yield.CancellationToken`. For example:
```
  new AsyncEnumerable<int>(async yield =>
  {
    try
    {
      ...
      yield.CancellationToken.ThrowIfCancellationRequested();
      ...
    }
    catch (OperationCanceledException)
    {
       // Graceful clean-up
       ...
    }
  });
```
This also gives an ability to ignore the cancellation, or implement an advanced logic with combining multiple cancellation tokens inside the loop body, compared to a simple loop termination.

What thoughts do you have on this approach?

**Comment by ndani14-zap** [comment]
The approach seems quite practical. It was just surprising. Thanks I'll close this issue :)
