### ISSUE TITLE
.NET Core 3 / .NET Standard 2.1

### ISSUE THREAD

**Issue by Numpsy** [Dasync/AsyncEnumerable#46]
Hi,

I see that the most recent version of the library has been adapted to use the built in IAsyncEnumerable in .NET Core 3, but can I ask what the situation is with .NET Standard 2.1? (from a quick test, looks like it uses its own definition there rather than the built in version?).

Thanks.

**Comment by kind-serge** [comment]
@Numpsy, with the yesterday's official release of NET Core 3 and NET Standard 2.1 this library has been updated as well. Thanks for waiting!

**Comment by silkfire** [comment]
@kind-serge Does an implementation of `ParallellForEachAsync` exist in .NET Core 3.0 or should we keep using your library?

**Comment by kind-serge** [comment]
@silkfire to my best knowledge `ParallellForEachAsync` does not exist in the latest .NET BCL and I have no info on whether it will be added or not. Keep using this library for now.

**Comment by Numpsy** [comment]
On a sort of related note - Microsoft have released a Microsoft.Bcl.AsyncInterfaces package that has definitions of IAsyncEnumerable and such for versions of .NET prior to Standard 2.1.

Any thoughts on using ParallellForEachAsync with those definitions?

**Comment by kind-serge** [comment]
@Numpsy , thanks for the info! I was not aware of that package.
Apparently it works for .NET Standard 2.0 only and no lower versions.
It is an easy change, however will have to bump the major version of this library to accommodate these changes.

**Comment by kind-serge** [comment]
@Numpsy , the new version has been released: https://www.nuget.org/packages/AsyncEnumerator/4.0.0

**Comment by Numpsy** [comment]
Thanks, I'll give it a go.

**Comment by Numpsy** [comment]
I tried it in a .Net Standard 2.0 library called from a .Net 4.7.2 application and hit some errors about missing methods, i'm guessing because the library is using the interface definitions from the Microsoft package, but the build for the app is pulling in the .Net 4.5 build of AsyncEnumerator that doesn't contain matching methods? 
(The Microsoft.Bcl.AsyncInterfaces package does actually appear to contain a build for .Net 4.6.1 on top of the .Net standard version, so I think the app sees those ok.)

**Comment by kind-serge** [comment]
Seems like a .NET Fx 4.6.1 (and higher) project uses the .NET Fx 4.5 version of the library instead of .NET Std 2.0. I updated the NuGet Package with the .NET Fx 4.6.1 version of this library to be compatible with .NET Std 2.0 projects: https://www.nuget.org/packages/AsyncEnumerator/4.0.1

**Comment by Numpsy** [comment]
Thanks, that seems ok now.
