### ISSUE TITLE
Take slow for large count value regardless of enumerable size

### ISSUE THREAD

**Issue by danylofitel** [Dasync/AsyncEnumerable#49]
Take() extension method is really slow when specifying large values of count (a billion or higher), even on empty enumerables. For example, the below code takes over 10 seconds to run:

`List<int> result = await Enumerable.Empty<int>().ToAsyncEnumerable().Take(1000000000).ToListAsync();`

Looking at source code (IAsyncEnumerableExtensions.cs), it seems that it's doing exactly count iterations without breaking from the loop as soon as HasNext returns false:

`

            private static async Task _enumerate(AsyncEnumerator<TSource>.Yield yield, TakeContext<TSource> context)
            {
                var enumerator = context.Source.GetAsyncEnumerator(yield.CancellationToken);
                try
                {
                    for (var i = context.Count; i > 0; i--)
                    {
                        if (await enumerator.MoveNextAsync().ConfigureAwait(false))
                            await yield.ReturnAsync(enumerator.Current).ConfigureAwait(false);
                    }
                }
                finally
                {
                    await enumerator.DisposeAsync().ConfigureAwait(false);
                }
            }

`

Either breaking the loop in else clause, or checking the condition in the loop control should allow for early exit if there's no more items left.

Pull request https://github.com/Dasync/AsyncEnumerable/pull/50

BTW, thanks for the great package!

**Comment by kind-serge** [comment]
Good finding, @danylofitel ! And I'm glad that you've found this library useful :)
The changes look good and will publish the new version shortly.

**Comment by kind-serge** [comment]
@danylofitel, the new [version 4.0.2](https://www.nuget.org/packages/AsyncEnumerator/4.0.2) has been published with your changes. Cheers!

**Comment by danylofitel** [comment]
Thanks for publishing so quickly :) Cheers!
